# Generated by Django 6.0.2 on 2026-02-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('concluida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
